### ISSUE TITLE
FR5. Social Media Links

### ISSUE THREAD

**Issue by miqdadhafiz35** [WSU-4110/sports-social-media-profile-locater#11]
|FR5. Social Media Links|
|---|
|**Goal**: When a player card is displayed the social media profile links for said player is listed as icons
**Stakeholders:** User|
| **Description:** When the user selects a team they'd like to view, the entire roster of said team will show. Each player will have their own player card with links of their social media profiles provided. They three social media platforms that links will be provided to are Twitter, Instagram, and Facebook  |
| **Origin:** Based on initial project specification   document, team 
members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 02/15/2022
|  **Priority:** 3|

**Comment by muhtacinm** [comment]
Backend implemented by @muhtacinm and @dettloffd 
Frontend implemented by @ManmeetBhogal
