### ISSUE TITLE
FR4. Landing Page

### ISSUE THREAD

**Issue by miqdadhafiz35** [WSU-4110/sports-social-media-profile-locater#7]
|FR4.  Landing Page|
|---|
|**Goal**: On the landing page, all thirty teams in the NBA are listed
**Stakeholders:** User|
| **Description:** When the user first opens the website or application, the landing page will contain, by default, all thirty teams in the NBA. They will have their logos as buttons so the user can select the team they'd like to view. |
| **Origin:** Based on initial project specification   document, team 
members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 02/15/2022
|  **Priority:** 3 |

**Comment by muhtacinm** [comment]
Frontend implemented by @miqdadhafiz35, @ManmeetBhogal, and @sayemk23 
Backend implemented by @muhtacinm and @dettloffd
